### ISSUE TITLE
Add font section

### ISSUE THREAD

**Issue by karim-dev-coder** [TrackMan/Unity.Package.FigmaToUnity#3]
If there is excellent code for working with fonts in the codebase, however, there is no documentation on it. It's particularly unclear that fonts need to be loaded separately and placed in the 'Fonts' folder relative to the Test script.

**Comment by anton-trackman** [comment]
Dear @karim-dev-coder, my sincere apologies for not resolving the issue for such a long time. I have added information to the Readme; please check the 'Folders Layout' section. Essentially, all you need to do is place your custom font in the 'Fonts' folder,  which should be in the same directory as the UXML file.
If you experience any other troubles - do not hesitate to reach us, we will be right here to help you!
