### ISSUE TITLE
ArgumentException: Requested Value 'CONNECTOR' was not found.

### ISSUE THREAD

**Issue by TarAlacrin** [TrackMan/Unity.Package.FigmaToUnity#8]
I get this error whenever I try and import something from my figma. Ive followed the steps in the Readme multiple times and gone up and down, the API Key works, and the page title is correct. I Reconfigured Test.cs to point to my page and asset; "SEEK | Final Assets & Delivery/Pilot" And it isn't throwing the error that it throws if it can't find the asset so it seems like the path is valid.

When I hit "Update UI & Images" the Background task launches, gets to 40% (2/5) and then breaks and gives this error. I tried googling but couldn't find anywhere where this issue was coming up. Just wondering if you had any idea what might be going wrong or how to fix it

> ArgumentException: Requested value 'CONNECTOR' was not found.
System.Enum+EnumResult.SetFailure (System.Enum+ParseFailureKind failure, System.String failureMessageID, System.Object failureMessageFormatArgument) (at <ecf276dcb8654fa5bed2c5ea1a4ad870>:0)
System.Enum.TryParseEnum (System.Type enumType, System.String value, System.Boolean ignoreCase, System.Enum+EnumResult& parseResult) (at <ecf276dcb8654fa5bed2c5ea1a4ad870>:0)
System.Enum.Parse (System.Type enumType, System.String value, System.Boolean ignoreCase) (at <ecf276dcb8654fa5bed2c5ea1a4ad870>:0)
System.Enum.Parse (System.Type enumType, System.String value) (at <ecf276dcb8654fa5bed2c5ea1a4ad870>:0)
Figma.global.ArrayConverter`2[T,TEnum].GetValue (Newtonsoft.Json.Linq.JObject obj, System.String name) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:52)
Figma.global.SceneNodeArrayConverter.ToObject (Newtonsoft.Json.Linq.JObject obj, Newtonsoft.Json.JsonSerializer serializer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:170)
Figma.global.ArrayConverter`2[T,TEnum].ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:42)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Linq.JToken.ToObject (System.Type objectType, Newtonsoft.Json.JsonSerializer jsonSerializer) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Linq.JToken.ToObject[T] (Newtonsoft.Json.JsonSerializer jsonSerializer) (at <761cf2a144514d2291a678c334d49e9b>:0)
Figma.global.SceneNodeArrayConverter.ToObject (Newtonsoft.Json.Linq.JObject obj, Newtonsoft.Json.JsonSerializer serializer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:173)
Figma.global.ArrayConverter`2[T,TEnum].ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:42)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList (System.Collections.IList list, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonSerializer.Deserialize[T] (Newtonsoft.Json.JsonReader reader) (at <761cf2a144514d2291a678c334d49e9b>:0)
Trackman.JsonUtilityShared`1[Gen].FromJson[T] (System.String json, System.Boolean useArrayPool) (at ./Library/PackageCache/com.trackman.commonutils@4cd37e1094/Runtime/Scripts/Interface/Core/JsonUtility.cs:374)
Figma.Inspectors.FigmaApi+<>c__DisplayClass5_0`1[T].<ConvertOnBackgroundAsync>b__0 () (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaApi.cs:35)
System.Threading.Tasks.Task`1[TResult].InnerInvoke () (at <ecf276dcb8654fa5bed2c5ea1a4ad870>:0)
System.Threading.Tasks.Task.Execute () (at <ecf276dcb8654fa5bed2c5ea1a4ad870>:0)
--- End of stack trace from previous location where exception was thrown ---
Figma.Inspectors.FigmaApi.ConvertOnBackgroundAsync[T] (System.String json, System.Threading.CancellationToken token) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaApi.cs:35)
Figma.Inspectors.FigmaUpdater+<>c__DisplayClass13_0.<DownloadAssetsAsync>g__GetFilesAsync|0 () (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaUpdater.cs:109)
Figma.Inspectors.FigmaUpdater.DownloadAssetsAsync (System.String name, System.Boolean downloadImages, System.Collections.Generic.IReadOnlyCollection`1[T] elements, System.Boolean filter, System.Boolean systemCopyBuffer, System.Int32 progress, System.Threading.CancellationToken token) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaUpdater.cs:135)
Figma.Inspectors.FigmaInspector.UpdateTitleAsync (UnityEngine.UIElements.UIDocument document, Figma.Figma figma, System.Int32 progress, System.String title, System.String folder, System.String relativeFolder, System.String uxmlName, System.Boolean systemCopyBuffer, System.Boolean downloadImages, System.Collections.Generic.IReadOnlyCollection`1[T] fontDirs, System.Threading.CancellationToken token) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaInspector.cs:253)
Figma.Inspectors.FigmaInspector.UpdateTitleWithProgressAsync (UnityEngine.UIElements.UIDocument document, Figma.Figma figma, System.String title, System.Boolean downloadImages, System.Collections.Generic.IReadOnlyCollection`1[T] fontDirs, System.Boolean systemCopyBuffer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaInspector.cs:231)
Figma.Inspectors.FigmaInspector.<OnAssetGUI>g__Update|16_0 (System.Boolean downloadImages, System.Boolean forceUpdate) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaInspector.cs:110)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <ecf276dcb8654fa5bed2c5ea1a4ad870>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e509afeff7384f24a8f0ac30527ff01c>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <e509afeff7384f24a8f0ac30527ff01c>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <e509afeff7384f24a8f0ac30527ff01c>:0)

**Comment by ivan-trackman** [comment]
> I get this error whenever I try and import something from my figma. Ive followed the steps in the Readme multiple times and gone up and down, the API Key works, and the page title is correct. I Reconfigured Test.cs to point to my page and asset; "SEEK | Final Assets & Delivery/Pilot" And it isn't throwing the error that it throws if it can't find the asset so it seems like the path is valid.
> 
> When I hit "Update UI & Images" the Background task launches, gets to 40% (2/5) and then breaks and gives this error. I tried googling but couldn't find anywhere where this issue was coming up. Just wondering if you had any idea what might be going wrong or how to fix it
> 
> > ArgumentException: Requested value 'CONNECTOR' was not found.
> > System.Enum+EnumResult.SetFailure (System.Enum+ParseFailureKind failure, System.String failureMessageID, System.Object failureMessageFormatArgument) (at :0)
> > System.Enum.TryParseEnum (System.Type enumType, System.String value, System.Boolean ignoreCase, System.Enum+EnumResult& parseResult) (at :0)
> > System.Enum.Parse (System.Type enumType, System.String value, System.Boolean ignoreCase) (at :0)
> > System.Enum.Parse (System.Type enumType, System.String value) (at :0)
> > Figma.global.ArrayConverter`2[T,TEnum].GetValue (Newtonsoft.Json.Linq.JObject obj, System.String name) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:52) Figma.global.SceneNodeArrayConverter.ToObject (Newtonsoft.Json.Linq.JObject obj, Newtonsoft.Json.JsonSerializer serializer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:170) Figma.global.ArrayConverter`2[T,TEnum].ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:42)
> > Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Newtonsoft.Json.Linq.JToken.ToObject (System.Type objectType, Newtonsoft.Json.JsonSerializer jsonSerializer) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Newtonsoft.Json.Linq.JToken.ToObject[T] (Newtonsoft.Json.JsonSerializer jsonSerializer) (at <761cf2a144514d2291a678c334d49e9b>:0)
> > Figma.global.SceneNodeArrayConverter.ToObject (Newtonsoft.Json.Linq.JObject obj, Newtonsoft.Json.JsonSerializer serializer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:173)
> > Figma.global.ArrayConverter`2[T,TEnum].ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Core/JsonUtility.cs:42) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList (System.Collections.IList list, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0) Newtonsoft.Json.JsonSerializer.Deserialize[T] (Newtonsoft.Json.JsonReader reader) (at <761cf2a144514d2291a678c334d49e9b>:0) Trackman.JsonUtilityShared`1[Gen].FromJson[T] (System.String json, System.Boolean useArrayPool) (at ./Library/PackageCache/com.trackman.commonutils@4cd37e1094/Runtime/Scripts/Interface/Core/JsonUtility.cs:374)
> > Figma.Inspectors.FigmaApi+<>c__DisplayClass5_0`1[T].<ConvertOnBackgroundAsync>b__0 () (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaApi.cs:35) System.Threading.Tasks.Task`1[TResult].InnerInvoke () (at :0)
> > System.Threading.Tasks.Task.Execute () (at :0)
> > --- End of stack trace from previous location where exception was thrown ---
> > Figma.Inspectors.FigmaApi.ConvertOnBackgroundAsync[T] (System.String json, System.Threading.CancellationToken token) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaApi.cs:35)
> > Figma.Inspectors.FigmaUpdater+<>c__DisplayClass13_0.g__GetFilesAsync|0 () (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaUpdater.cs:109)
> > Figma.Inspectors.FigmaUpdater.DownloadAssetsAsync (System.String name, System.Boolean downloadImages, System.Collections.Generic.IReadOnlyCollection`1[T] elements, System.Boolean filter, System.Boolean systemCopyBuffer, System.Int32 progress, System.Threading.CancellationToken token) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaUpdater.cs:135) Figma.Inspectors.FigmaInspector.UpdateTitleAsync (UnityEngine.UIElements.UIDocument document, Figma.Figma figma, System.Int32 progress, System.String title, System.String folder, System.String relativeFolder, System.String uxmlName, System.Boolean systemCopyBuffer, System.Boolean downloadImages, System.Collections.Generic.IReadOnlyCollection`1[T] fontDirs, System.Threading.CancellationToken token) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaInspector.cs:253)
> > Figma.Inspectors.FigmaInspector.UpdateTitleWithProgressAsync (UnityEngine.UIElements.UIDocument document, Figma.Figma figma, System.String title, System.Boolean downloadImages, System.Collections.Generic.IReadOnlyCollection`1[T] fontDirs, System.Boolean systemCopyBuffer) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaInspector.cs:231)
> > Figma.Inspectors.FigmaInspector.g__Update|16_0 (System.Boolean downloadImages, System.Boolean forceUpdate) (at ./Library/PackageCache/com.trackman.figma@0de8983bc9/Editor/Inspector/FigmaInspector.cs:110)
> > System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.b__7_0 (System.Object state) (at :0)
> > UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at :0)
> > UnityEngine.UnitySynchronizationContext.Exec () (at :0)
> > UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at :0)

Hey, I think we need to add this special enum to our codebase

**Comment by anton-trackman** [comment]
Hi @TarAlacrin , the issue is fixed, pull the latest update.
